# Generated by Django 2.0 on 2022-01-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='numEscanyos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Seats'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='tipo',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('HUNTINGTONHILL', 'HUNTINGTONHILL'), ('DHONT', 'DHONT'), ('HAMILTON', 'HAMILTON'), ('BIPARTITANSHIP', 'BIPARTITANSHIP'), ('IMPERIALI', 'IMPERIALI'), ('SAINTELAGUE', 'SAINTELAGUE')], default='IDENTITY', max_length=20, verbose_name='Count method'),
        ),
    ]
