# Generated by Django 2.0 on 2022-01-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20220108_1835'),
        ('voting', '0005_auto_20220103_1037'),
    ]

    operations = [
    ]
